project:
  type: book
  output-dir: docs

book:
  twitter-card: true
  title: "Creating Effective Display Tables with the gt Package"
  author: "Richard Iannone"
  search: true
  repo-url: https://github.com/rich-iannone/gt-effective-display-tables
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-table-components.qmd
    - 03-formatting-values.qmd
    - 04-modifying-columns.qmd
    - 05-summary-rows-columns.qmd
    - 06-table-options.qmd
    - 07-footnotes-source-notes.qmd
    - 08-nanoplots.qmd
    - 09-output-formats.qmd
    - 10-extension-packages.qmd
    - 11-creating-extensions.qmd

format:
  html:
    toc: true
    toc-depth: 2
    code-link: true
    code-line-numbers: false
    code-annotations: below

execute:
  collapse: true

html-table-processing: none
