project:
  type: book
  output-dir: docs

book:
  twitter-card: true
  title: "Creating Effective Display Tables with the **gt** Package"
  author: "Richard Iannone"
  search: true
  repo-url: https://github.com/rich-iannone/gt-effective-display-tables
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
        - 01-introduction.qmd
        - 02-table-components.qmd
    - part: "Formatting Data"
      chapters:
        - 03-formatting-numbers.qmd
        - 04-formatting-dates-text.qmd
        - 05-substitution-transformation.qmd
    - part: "Table Structure"
      chapters:
        - 06-modifying-columns.qmd
        - 07-summary-rows-columns.qmd
    - part: "Styling and Presentation"
      chapters:
        - 08-table-styling-options.qmd
        - 09-footnotes-source-notes.qmd
        - 10-nanoplots.qmd
    - part: "Advanced Topics"
      chapters:
        - 11-table-groups.qmd
        - 12-output-formats.qmd
    - part: "Extending gt"
      chapters:
        - 13-extension-packages.qmd
        - 14-creating-extensions.qmd
  appendices:
    - appendix-reference.qmd
    - appendix-datetime-patterns.qmd
    - appendix-datasets.qmd

format:
  html:
    toc: true
    toc-depth: 2
    code-link: true
    code-line-numbers: false
    code-annotations: below
    css: custom.css

execute:
  collapse: true

html-table-processing: none
